src/recsys_django/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signup_success/', views.SignupSuccessView.as_view(), name='signup_success'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

src/recsys_django/offline/urls.py
from django.urls import path
from . import views

app_name = 'offline'
urlpatterns = [
    path('update/', views.UpdateView.as_view(), name='update'),
]

src/recsys_django/online/urls.py
from django.urls import path
from . import views

app_name = 'online'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('random/', views.RandomView.as_view(), name='random'),
    path('popularity/', views.PopularityView.as_view(), name='popularity'),
    path('<int:item_id>/similarity/', views.SimilarityView.as_view(), name='similarity'),
    path('itemcf/', views.ItemcfView.as_view(), name='itemcf'),
    path('<int:item_id>/rating/', views.RatingView.as_view(), name='rating'),
]

src/recsys_django/recsys_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('online.urls')),
    path('', include('accounts.urls')),
    path('', include('offline.urls'))
]

urlpatterns += static(
    # MEDIA_URL = 'media/'
    settings.MEDIA_URL,
    # MEDIA_ROOTにリダイレクト
    document_root=settings.MEDIA_ROOT
)

src/recsys_django/online/models.py
from django.db import models


class User(models.Model):
    """ユーザモデル

    Attributes
    ----------
    user_id : IntegerField
        ユーザID
    name : TextField
        ユーザ名
    age : IntegerField
        年齢
    sex : CharField
        性別
    """
    user_id = models.IntegerField(primary_key=True)
    name = models.TextField()
    age = models.IntegerField(blank=True, null=True)
    sex = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'users'

    def __str__(self):
        return '{}:{}'.format(self.user_id, self.name)


class Item(models.Model):
    """アイテムモデル

    Attributes
    ----------
    item_id : IntegerField
        アイテムID
    name : TextField
        アイテム名
    red : IntegerField
        赤身の特徴量
    white : IntegerField
        白身の特徴量
    shining : IntegerField
        光物の特徴量
    """
    item_id = models.IntegerField(primary_key=True)
    name = models.TextField()
    red = models.IntegerField(blank=True, null=True)
    white = models.IntegerField(blank=True, null=True)
    shining = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'items'

    def __str__(self):
        return '{}:{}'.format(self.item_id, self.name)


class Rating(models.Model):
    """評価値モデル

    Attributes
    ----------
    user : ForeignKey[User]
        対象ユーザ
    item : ForeignKey[Item]
        対象アイテム
    rating : IntegerField
        評価値
    """
    user = models.ForeignKey(User, models.CASCADE)
    item = models.ForeignKey(Item, models.CASCADE)
    rating = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'ratings'

    def __str__(self):
        return '{}:{}:{}'.format(self.user_id, self.item_id, self.rating)


class ReclistPopularity(models.Model):
    """人気ベース推薦リストモデル

    Attributes
    ----------
    rank : FloatField
        推薦順位
    item : ForeignKey[Item]
        推薦アイテム
    score : FloatField
        推薦スコア
    """
    rank = models.FloatField()
    item = models.ForeignKey(Item, models.CASCADE)
    score = models.FloatField()

    class Meta:
        managed = False
        db_table = 'reclist_popularity'

    def __str__(self):
        return '{}:{}:{}'.format(self.rank, self.item, self.score)


class ReclistSimilarity(models.Model):
    """アイテム類似度ベース推薦リストモデル

    Attributes
    ----------
    base_item : ForeignKey[Item]
        ベースアイテム
    rank : FloatField
        推薦順位
    item : ForeignKey[Item]
        推薦アイテム
    score : FloatField
        推薦スコア
    """
    base_item = models.ForeignKey(Item, models.CASCADE, related_name='base_item')
    rank = models.FloatField()
    item = models.ForeignKey(Item, models.CASCADE)
    score = models.FloatField()

    class Meta:
        managed = False
        db_table = 'reclist_similarity'

    def __str__(self):
        return '{}:{}:{}:{}'.format(self.base_item, self.rank, self.item, self.score)


class ReclistItemcf(models.Model):
    """アイテムベース協調フィルタリングに基づく推薦リストモデル

    Attributes
    ----------
    user : ForeignKey[User]
        対象ユーザ
    rank : FloatField
        推薦順位
    item : ForeignKey[Item]
        推薦アイテム
    score : FloatField
        推薦スコア
    """
    user = models.ForeignKey(User, models.CASCADE)
    rank = models.FloatField()
    item = models.ForeignKey(Item, models.CASCADE)
    score = models.FloatField()

    class Meta:
        managed = False
        db_table = 'reclist_itemcf'

    def __str__(self):
        return '{}:{}:{}:{}'.format(self.user, self.rank, self.item, self.score)

src/recsys_django/online/views.py
import json

from django.views.generic import View
from django.shortcuts import render
from django.http import HttpResponse

from .models import Item, Rating, ReclistPopularity, ReclistSimilarity, ReclistItemcf
from .mappers import RecRandomMapper, RecPopularityMapper, RecSimilarityMapper, RecItemcfMapper


class IndexView(View):
    """インデックスビュー

    Attributes
    ----------
    context: dict
        コンテキスト
    """

    def __init__(self):
        self.context = {}

    def get(self, request, *args, **kwargs):
        """index.htmlをレンダリングしたレスポンスを取得する。

        Parameters
        ----------
        request : WSGIRequest
            リクエスト

        Returns
        -------
        HttpResponse
            index.htmlをレンダリングしたレスポンスを返す。
        """
        return render(request, 'index.html', self.context)


class RandomView(View):
    """ランダム推薦ビュー
    """

    def get(self, request, *args, **kwargs):
        """ランダム推薦リストを取得する。

        Parameters
        ----------
        request : WSGIRequest
            リクエスト

        Returns
        -------
        HttpResponse
            推薦説明と推薦リストをJSON形式で返す。
        """
        # オブジェクトの取得
        reclist = list(Item.objects.order_by('?'))
        recs = [RecRandomMapper(rec).as_dict() for rec in reclist]

        # レスポンスの生成
        description = '本日のおすすめ'
        response = {
            'description': description,
            'reclist': recs,
        }
        response_json = json.dumps(response)

        # レスポンスの返却
        return HttpResponse(response_json, content_type='application/json')


class PopularityView(View):
    """人気ベース推薦ビュー
    """

    def get(self, request, *args, **kwargs):
        """人気ベース推薦リストを取得する。

        Parameters
        ----------
        request : WSGIRequest
            リクエスト

        Returns
        -------
        HttpResponse
            推薦説明と推薦リストをJSON形式で返す。
        """
        # オブジェクトの取得
        reclist = ReclistPopularity.objects.all()
        recs = [RecPopularityMapper(rec).as_dict() for rec in reclist]

        # レスポンスの生成
        description = '人気の寿司'
        response = {
            'description': description,
            'reclist': recs,
        }
        response_json = json.dumps(response)

        # レスポンスの返却
        return HttpResponse(response_json, content_type='application/json')


class SimilarityView(View):
    """アイテム類似度ベース推薦ビュー
    """

    def get(self, request, item_id, *args, **kwargs):
        """アイテム類似度ベース推薦リストを取得する。

        Parameters
        ----------
        request : WSGIRequest
            リクエスト
        item_id : int
            ベースアイテムのアイテムID

        Returns
        -------
        HttpResponse
            推薦説明と推薦リストをJSON形式で返す。
        """
        # オブジェクトの取得
        base_item = Item.objects.get(pk=item_id)
        reclist = ReclistSimilarity.objects.filter(base_item_id=item_id)
        recs = [RecSimilarityMapper(rec).as_dict() for rec in reclist]

        # レスポンスの生成
        description = base_item.name + 'が好きな人はこんな寿司も好きです。'
        response = {
            'description': description,
            'reclist': recs,
        }
        response_json = json.dumps(response)

        # レスポンスの返却
        return HttpResponse(response_json, content_type='application/json')


class ItemcfView(View):
    """アイテムベース協調フィルタリングビュー
    """

    def get(self, request, *args, **kwargs):
        """アイテムベース協調フィルタリングによる推薦リストを取得する。

        Parameters
        ----------
        request : WSGIRequest
            リクエスト

        Returns
        -------
        HttpResponse
            推薦説明と推薦リストをJSON形式で返す。
        """
        if not request.user.is_authenticated:
            # 対象ユーザがログイン状態でない場合
            response = {
                'description': None,
            }
            response_json = json.dumps(response)
            return HttpResponse(response_json, content_type='application/json')

        # オブジェクトの取得
        user = request.user.user
        # オブジェクトの取得
        reclist = ReclistItemcf.objects.filter(user_id=user.user_id)
        recs = [RecItemcfMapper(rec).as_dict() for rec in reclist]

        # レスポンスの生成
        description = user.name + 'さんにおすすめ'
        response = {
            'description': description,
            'reclist': recs,
        }
        response_json = json.dumps(response)

        # レスポンスの返却
        return HttpResponse(response_json, content_type='application/json')


class RatingView(View):
    """評価値ビュー
    """

    def get(self, request, item_id, *args, **kwargs):
        """対象ユーザの対象アイテムの評価値を取得する。

        Parameters
        ----------
        request : WSGIRequest
            リクエスト
        item_id : int
            対象アイテムのアイテムID

        Returns
        -------
        HttpResponse
            対象ユーザの対象アイテムの評価値をJSON形式で返す。
            対象ユーザがログイン状態でなければ{'rating': -1}を返す。
            対象ユーザが対象アイテムに対して未評価の場合、{'rating': 0}を返す。
        """
        if not request.user.is_authenticated:
            # 対象ユーザがログイン状態でない場合
            response = {
                'rating': -1,
            }
            response_json = json.dumps(response)
            return HttpResponse(response_json, content_type='application/json')

        # オブジェクトの取得
        user = request.user.user
        item = Item.objects.get(pk=item_id)
        rating_model = Rating.objects.filter(user=user, item=item).first()
        rating = rating_model.rating if rating_model is not None else 0

        # レスポンスの生成
        response = {
            'rating': rating,
        }
        response_json = json.dumps(response)

        # レスポンスの返却
        return HttpResponse(response_json, content_type='application/json')

    def post(self, request, item_id, *args, **kwargs):
        """対象ユーザの対象アイテムに対する評価値を登録する。

        Parameters
        ----------
        request : WSGIRequest
            リクエスト
        item_id : int
            対象アイテムのアイテムID

        Returns
        -------
        HttpResponse
            対象ユーザがログイン状態でなければ{'rating': -1}を返す。
            対象ユーザが対象アイテムに対して未評価の場合、{'rating': 0}を返す。
        """
        if not request.user.is_authenticated:
            # 対象ユーザがログイン状態でない場合
            response = {
                'user_id': None,
            }
            response_json = json.dumps(response)
            return HttpResponse(response_json, content_type='application/json')

        # リクエストの取得
        rating = request.POST.get('rating')

        # オブジェクトの取得
        user = request.user.user
        item = Item.objects.get(pk=item_id)

        # モデルの更新
        rating_model = Rating.objects.filter(user=user, item=item).first()
        # データの追加，更新
        if rating_model is not None:
            rating_model.rating = rating
            rating_model.save()
        else:
            rating_model = Rating(user=user, item=item, rating=rating)
            rating_model.save()

        # レスポンスの生成
        response = {
        }
        response_json = json.dumps(response)

        # レスポンスの返却
        return HttpResponse(response_json, content_type='application/json')

src/recsys_django/online/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!-- Bootstrapサンプルのnavbar-staticをコピーして編集する。 -->
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Hugo 0.84.0">
        <title>{% block title %}{% endblock %}</title>

        {# --- css --- #}
        <!-- Custom styles for this template -->
        <link href="{% static 'css/navbar-top.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>
    <body>
        {# --- js --- #}
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

        {# --- files --- #}
        <script>
            let returnSrc = "{% static 'img/return.png' %}";
            let starSrcs = new Array(
                "{% static 'img/star0.png' %}",
                "{% static 'img/star1.png' %}",
                "{% static 'img/star2.png' %}",
            );
        </script>

        <!-- ナビゲーションバー -->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="navbar-brand" href="{% url 'online:index' %}">recsys-django</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav mr-auto mb-2 mb-md-0">
                        {% if user.is_authenticated %}
                            <!-- ログイン中のメニュー -->
                            <div class="dropdown">
                                <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user.username }}
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">ログアウト</a></li>
                                </ul>
                            </div>
                        {% else %}
                            <!-- ログイン状態ではない場合のメニュー -->
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:signup' %}">サインアップ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:login' %}">ログイン</a>
                            </li>
                        {% endif %}
                    </ul>
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" formaction="{% url 'offline:update' %}">更新</button>
                    </form>
                </div>
            </div>
        </nav>

        <!-- メインコンテンツ -->
        <main class="container">
            {% block contents %}{% endblock %}
        </main>

        <!-- フッター -->
        <footer class="text-muted py-5">
            <div class="container">
                <p class="float-end mb-1">
                    <a href="{% url 'online:index' %}">トップページに戻る</a>
                </p>
                <p class="mb-1">
                    &copy; 2022 RecSysLab
                </p>
            </div>
        </footer>
    </body>
</html>

src/recsys_django/online/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}sushi recommender | recsys-django{% endblock %}

{% block contents %}

    <div class="col-md-12 text-center">
        <canvas id="main_canvas" width="720" height="750"></canvas>
    </div>

    {# --- js --- #}
    <script type="text/javascript" src="{% static 'js/Page.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/MainPage.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/DetailPage.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/Item.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/Component.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ItemComponent.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/NextButton.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/Slot.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ReturnButton.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/Star.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/StarRating.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ItemDetailComponent.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/csrftoken.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>

{% endblock %}